language: c++
sudo: false
dist: trusty
os:
- linux
- osx
addons:
  apt:
    packages:
    - libfreetype6-dev
    - libsdl2-dev
script:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sdl2; fi
- mkdir build
- cd build
- cmake ..
- make everything
env:
  global:
  - CFLAGS="-Wdeclaration-after-statement -Werror"
  - CXXFLAGS="-Werror"
